server:
  port: 8080

app:
  input-root: ${APP_INPUT_ROOT:/input}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://[::1]:5433/filedb}
    username: ${SPRING_DATASOURCE_USERNAME:fileuser}
    password: ${SPRING_DATASOURCE_PASSWORD:filepass}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html